title: Dehydrate
author: Florent Barbault
email: florent.barbault@u-paris.fr
description: a simple script to remove water molecules on MD trajectory
twitter_username: BarbaultFlorent

theme: jekyll-theme-slate

